receivers:
  otlp:
    protocols:
      http:
        cors:
            allowed_origins:
            - http://*
            - https://*
        endpoint: 0.0.0.0:4318

processors:

  memory_limiter:
      check_interval: 1s
      limit_percentage: 65
      spike_limit_percentage: 20

  filter:
      metrics:
        exclude:
          match_type: regexp
          metric_names: ["rpc\\.client\\..*"]

  batch:
    timeout: 10s
    send_batch_size: 500
  
  resourcedetection:
    detectors: [gcp]
    timeout: 5s

exporters:
  googlecloud:
    project: gcp-myproject-pcd
    metric:
      prefix: custom.googleapis.com/
  debug:
    verbosity: detailed

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  googleclientauth:

service:
  extensions: [health_check, googleclientauth] 
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, filter, batch]
      exporters: [googlecloud, debug]
  telemetry:
    logs:
      level: debug